### ISSUE TITLE
Reset Agent doesn't work

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/meta-device-cloud#12]
I'm running it from the command line and I changed to the /etc/python-device-manager directory to start it. 

It stops the device manager but fails to restart it.

ov 30 15:57:41 DEBUG: handler.py:1003 - MQTT sent 0003
Nov 30 15:57:41 DEBUG: handler.py:989 - Received message on topic "reply/0003"
{
  "1": {
    "params": {
      "messages": [
        {
          "command": "method.exec", 
          "expires": "2017-11-30T15:59:41.804Z", 
          "from": "julia.keffer@windriver.com", 
          "id": "5a202a7574e93617142770cd", 
          "params": {
            "method": "reset_agent", 
            "thingDefKey": "hdc_device_manager_def"
          }, 
          "thingKey": "85356677-f8c9-4098-9578-277904aff540-device_manager_py"
        }
      ]
    }, 
    "success": true
  }
}
Nov 30 15:57:41 INFO: handler.py:648 - Received success for 0003-1 - Mailbox Check
Nov 30 15:57:41 INFO: handler.py:375 - Disconnecting...
Nov 30 15:57:41 INFO: handler.py:383 - Waiting for replies...
Unknown operation restart device-manager.

**Comment by element-82** [comment]
This requires the device manager to be run as a service.  It will do a systemctl restart device-manager.
