### ISSUE TITLE
README.WRL9.md requires refresh

### ISSUE THREAD

**Issue by mafoglia** [Wind-River/meta-device-cloud#16]
This README should be updated.
-The 'git clone' should probably refer to Wind River's instructions(i.e. WindShare) for WRL9 installation.
-Some of the 'add-layer' commands appear to be unnecessary, i.e. layer already present message.
-The 'add-layer' command for '../../repos/meta...' resulted in layer not found (_IIRC_)

These instructions will use the HEAD of device-cloud-python repo, which may not be the released version.  Can a note be added which details how to checkout a released version(i.e. how to use a bbappend file)?

**Comment by jkeffer** [comment]
The intel-x86-64 value for the --machines option is no longer valid. genericx86-64 works.

The add-layer command Mike mentions should be ../layers/meta-openembedded/meta-oe, but again, it returns already present.
