### ISSUE TITLE
README.IDP.md requires refresh

### ISSUE THREAD

**Issue by ccassidy-wrs** [Wind-River/meta-device-cloud#18]
Can we update the workflow in the readme, following the release of IDP RCPL 27 and support for Python 2.7.9.

For example:
- do we still require the oe-core layer from stash?
- do we still require the openembedded layer from WRL9?

Ideally we want a workflow where customers can use standard layers.

**Comment by tonym-wrs** [comment]
Closed as of pull #19  Commit: https://github.com/Wind-River/meta-device-cloud/commit/bc35108f00dc549431e041fa44fc8d0f05a700e1
