### ISSUE TITLE
Warning with Yocto-build: post(python-device-cloud-1.0-r0.i586) scriptlet failed

### ISSUE THREAD

**Issue by PhilippMichelWind** [Wind-River/meta-device-cloud#24]
Evaluation-customer reports the following issue, when building for their own rocko-based Yocto Linux:

    warning: %post(python-device-cloud-1.0-r0.i586) scriptlet failed, exit status 1

see build output below:

Running useradd commands...
NOTE: systemd: Performing useradd with [--root /mnt/data/poky-build/build/tmp/work/qemux86-poky-linux/core-image-full-cmdline/1.0-r0/rootfs  --system -d / -M --shell /bin/nologin systemd-bus-proxy]
  Installing       : systemd-extra-utils-1:234-r0.i586                  279/308 
  Installing       : packagegroup-core-ssh-openssh-1.0-r1.noarch        280/308 
  Running scriptlet: python-device-cloud-1.0-r0.i586                    281/308 
Running groupadd commands...
NOTE: python-device-cloud: Performing groupadd with [--root /mnt/data/poky-build/build/tmp/work/qemux86-poky-linux/core-image-full-cmdline/1.0-r0/rootfs -f -r -o -g 1005 dc]
Running useradd commands...
NOTE: python-device-cloud: Performing useradd with [--root /mnt/data/poky-build/build/tmp/work/qemux86-poky-linux/core-image-full-cmdline/1.0-r0/rootfs -r -s /usr/sbin/nologin -g 1005 dc]
  Installing       : python-device-cloud-1.0-r0.i586                    281/308 
  Running scriptlet: python-device-cloud-1.0-r0.i586                    281/308 
**_warning: %post(python-device-cloud-1.0-r0.i586) scriptlet failed, exit status 1_**
  Installing       : psplash-default-0.1+git0+2015f7073e-r15.i586       282/308 
  Running scriptlet: psplash-default-0.1+git0+2015f7073e-r15.i586       282/308 
update-alternatives: Linking /mnt/data/poky-build/build/tmp/work/qemux86-poky-linux/core-image-full-cmdline/1.0-r0/rootfs/usr/bin/psplash to /usr/bin/psplash-default

**Comment by element-82** [comment]
fixed by f5e684d1805e2bdc2962ec75c2239bebff63c742
