### ISSUE TITLE
Rename watchdog to match Python SDK

### ISSUE THREAD

**Issue by ccassidy-wrs** [Wind-River/meta-device-cloud#27]
Now that rollback watchdog is renamed in SDK "device-cloud-python", it also needs to be renamed in file device-cloud-common.inc.

**Comment by element-82** [comment]
Chris,
it was fixed here:
https://github.com/Wind-River/device-cloud-python/commit/35b70a5960c4cd8a9560d760027d72c79b468b47

The meta layer pulls the last release.  If you want to test it , you can edit recipes-iot/python/release.inc
