### ISSUE TITLE
Yocto (non-IDP) builds are broken

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/meta-device-cloud#3]
I built for WR Linux 9 and got the following warning: 

WARNING: No recipes available for:
  /buildarea1/jkeffer/meta-device-cloud/recipes-initramfs/ramfs-init/ramfs-init_1.0.bbappend

In the recipe file, it exits for non-IDP builds. When I build the image, the files I would expect to find in sysroots are not there. It doesn't look like there are any device cloud files in the image.

**Comment by element-82** [comment]
Fixed here c8b81c1cd03b695651ff7977f349aad547fc7ff1
