### ISSUE TITLE
Readme for Yocto builds needs more details

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/meta-device-cloud#4]
List the build steps explicitly, including the bitbake add layers and what image to build, or at least an example of what image to build.

Add details about what to put in the layer.conf to add a telnet server to the image. 

Additional information should indicate that this readme applies to WR Linux 9.

**Comment by element-82** [comment]
This was fixed c8b81c1cd03b695651ff7977f349aad547fc7ff1
